#This YML file is to be used specificially for the SDraw package. Other packages will require different YML file contents.
#Use R language
language: r
sudo: true
cache: packages
warnings_are_errors: false

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings" #don't build the vignettes or manual
    - _R_CHECK_TIMINGS_="0" #Allows for timing information for the examples of all functions
    - CODECOV_TOKEN="4326e078-039a-4eb4-9afe-a18423ea35f1" #test token to ensure this service actually works

r:
  - release

#Install external dependencies, such as rgeos. With the newest Travis-CI update that utilizes the Ubuntu 18 distro, 
#it would appear that the binaries "libudunits2-dev, and libgdal-dev" 
#are now necessary to test R software packages.
before_install:
  - sudo apt-get install libudunits2-dev
  - sudo apt-get install libgdal-dev
  - sudo apt-get install r-cran-rgeos

install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dependencies = TRUE)'
#This will catch installation issues
  - R -e 'devtools::install_github("semmons1/SDraw")'
  - R -e 'install.packages("sp")'
  - R -e 'install.packages("spsurvey")' #deldir is a dependency that should be installed with spsurvey
  - R -e 'install.packages("covr")' #specifically for codecovr feature

#Avoid building vignettes, they take too much time and will often time out the Travis CI  
script:
  - R CMD build --no-build-vignettes --no-manual .
  - R CMD check --no-build-vignettes --no-manual --timings *tar.gz

#report coverage for release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install();devtools::test()'

notifications:
  email:
    on_success: change
    on_failure: change
